### ISSUE TITLE
Creating new project fails: "file already exists"

### ISSUE THREAD

**Issue by jarcane** [filipesilva/create-cljs-app#10]
Attempting to create a new project fails as it appears to try to create the new directory twice, and the second attempt fails and quits the creation process. Stack trace below:

```
Creating a new CLJS app in C:\projects\shadow-cljs-on-glitch.
fs.js:113
    throw err;
    ^

Error: EEXIST: file already exists, mkdir 'C:\projects\shadow-cljs-on-glitch'
    at Object.mkdirSync (fs.js:729:3)
    at C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:264:110
    at C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:139:301
    at C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:139:314
    at nd (C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:109:54)
    at md.f.J (C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:111:225)
    at rb (C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:38:219)
    at Q (C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:52:81)
    at id.f.V (C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:102:349)
    at Wa (C:\Users\jarca\scoop\persist\nodejs\cache\_npx\34216\node_modules\create-cljs-app\dist\lib.js:29:54)
```

**Comment by filipesilva** [comment]
Well that's odd. 

What command did you use? Can you also tell me your node version please?

**Comment by filipesilva** [comment]
Off the top of my head I think it could happen with Node < 10.12.0, because I use it with the recursive option and that was only introduced in the mentioned version. I'll update the readme to reflect the real minimum as it lists 8 atm. Please let me know if that was it though.

**Comment by jarcane** [comment]
`npm init`, did it on both Windows and the Linux container on Glitch. Glitch is on Node 8 I think, my Windows machine is on Node 10.9.0. Upgrading to 13 seemed to fix it there, but I guess that makes Glitch a writeoff for now as I can't upgrade the node version there.

**Comment by filipesilva** [comment]
I had a look on https://glitch.com/help/node/ and it seems like these versions should be available:
```
v10.15.3
v11.14.0
v12.0.0
v6.17.1
v8.15.1
v9.11.2
```

**Comment by filipesilva** [comment]
It makes me think I should add the engine to my package.json though.

**Comment by prabhugopal** [comment]
Its just works fine.. 👍  Mine node *v10.15.3* on Mac..  
![image](https://user-images.githubusercontent.com/6929957/67526078-06191800-f682-11e9-9393-708629846c59.png)

**Comment by jarcane** [comment]
Thanks for the tip about Glitch Node version!

**Comment by filipesilva** [comment]
I think it's ok to close this issue now. I've updated the readme to list the real minimum version and added the engines field as well.

In general I'm not too keen on trying for Node 8 support since it's nearing EOL anyway.
