### ISSUE TITLE
Add a check for console errors in e2e

### ISSUE THREAD

**Issue by filipesilva** [filipesilva/create-cljs-app#26]
We should check if there are any console errors in the browser for the app e2e. 

According to https://github.com/getgauge/taiko/issues/913, https://github.com/saikrishna321/taiko-diagnostics#logconsoleinfo-command should do it.

**Comment by filipesilva** [comment]
taiko-diagnostics can print the logs, but doesn't expose them for checks. Logged a feature request: https://github.com/saikrishna321/taiko-diagnostics/issues/149

**Comment by saikrishna321** [comment]
https://github.com/saikrishna321/taiko-diagnostics/issues/149

**Comment by filipesilva** [comment]
I used it in https://github.com/filipesilva/create-cljs-app/pull/30 and it works great, thank you!
