### ISSUE TITLE
Cannot create a new project: "Cannot read property 'code' of null"

### ISSUE THREAD

**Issue by anttti** [filipesilva/create-cljs-app#3]
Creating a new project fails with the filesystem left intact (no `test-app` directory is created):

```
> npx create-cljs-app test-app
npx: installed 24 in 2.223s
Cannot read property 'code' of null
```

Running on
- macOS 10.14.6
- Node 12.12.0

**Comment by filipesilva** [comment]
Well that's unexpected and bad. Hm. 

Tell me please, do you have `yarn` on your system? And what about `git` of `java`, do you have those?

**Comment by anttti** [comment]
I don't have `yarn`, `git` 2.20.1 (the one that comes with macOS), my `java` is `openjdk 13 2019-09-17`.

**Comment by filipesilva** [comment]
Ok, I think I have some bad detection for yarn that is breaking things. If you'd like to install yar, I believe you'll be able to proceed right now. But I hope to have it fixed in a bit.

**Comment by filipesilva** [comment]
Yeah it should just fallback to `npm` when `yarn` isn't there. But the logic for detecting binaries wasn't working the way I thought.
