### ISSUE TITLE
Cannot create new project (Ubuntu 19.04)

### ISSUE THREAD

**Issue by iwsfutcmd** [filipesilva/create-cljs-app#4]
When running the command `npx create-cljs-app my-app`, the following error is returned:

```
npx: installed 24 in 1.633s
Cannot find module '../dist/lib'
Require stack:
- /home/iwsfutcmd/.npm/_npx/32025/lib/node_modules/create-cljs-app/bin/create-cljs-app.js
```

Similar errors are returned when using `npm init` and `yarn create`.

Currently running this on Ubuntu 19.04, Node v12.8.0

**Comment by filipesilva** [comment]
I think I botched the auto release process. It isn't building before releasing. Sorry about that, will fix!

**Comment by filipesilva** [comment]
@iwsfutcmd 0.1.10 is now out on NPM and it works as far as I can tell. Thanks for letting me know about this very nasty problem so quickly!
